-- recreate_public_schema.sql 
-- Recreate public schema tables, constraints, RLS, policies, and grants (DDL only).
-- Generated by assistant from project inspection.
-- Review function bodies and policy expressions before running.

BEGIN;

-- Ensure required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

SET search_path = public;

-- ==========================================
-- 1. TABLES
-- ==========================================

-- 1) Table: profiles
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY,
    display_name text,
    avatar_url text,
    wallet_balance integer DEFAULT 0 CHECK (wallet_balance >= 0),
    total_savings_rp integer DEFAULT 0 CHECK (total_savings_rp >= 0),
    level integer DEFAULT 1 CHECK (level >= 1),
    current_xp integer DEFAULT 0 CHECK (current_xp >= 0),
    max_xp integer DEFAULT 100 CHECK (max_xp > 0),
    health integer DEFAULT 100 CHECK (health >= 0 AND health <= 100),
    mood text DEFAULT 'neutral'::text CHECK (mood = ANY (ARRAY['happy'::text, 'neutral'::text, 'sick'::text])),
    accessories jsonb DEFAULT '[]'::jsonb,
    streak_days integer DEFAULT 0 CHECK (streak_days >= 0),
    recipes_cooked integer DEFAULT 0 CHECK (recipes_cooked >= 0),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    equipped_accessories jsonb DEFAULT '{}'::jsonb,
    streak integer DEFAULT 0,
    gold integer DEFAULT 0,
    last_active_date date,
    daily_cook_count integer DEFAULT 0,
    last_cook_reset_date date DEFAULT CURRENT_DATE,
    last_health_check_at timestamptz DEFAULT now(),
    consecutive_inactive_days integer DEFAULT 0,
    last_cook_date date,
    streak_shield_active boolean DEFAULT false,
    is_fainted boolean DEFAULT false,
    faint_recovery_count integer DEFAULT 0,
    friend_code character varying UNIQUE,
    recipes_saved integer DEFAULT 0 CHECK (recipes_saved >= 0)
);

-- 2) Table: food_logs
CREATE TABLE IF NOT EXISTS public.food_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid,
    food_name text,
    calories integer DEFAULT 0 CHECK (calories >= 0),
    protein numeric DEFAULT 0 CHECK (protein >= 0::numeric),
    carbs numeric DEFAULT 0 CHECK (carbs >= 0::numeric),
    fat numeric DEFAULT 0 CHECK (fat >= 0::numeric),
    sugar numeric DEFAULT 0 CHECK (sugar >= 0::numeric),
    sodium numeric DEFAULT 0 CHECK (sodium >= 0::numeric),
    health_grade text CHECK (health_grade = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text])),
    meal_type text CHECK (meal_type = ANY (ARRAY['breakfast'::text, 'lunch'::text, 'dinner'::text, 'snack'::text])),
    source text CHECK (source = ANY (ARRAY['vision_scan'::text, 'object_detection'::text, 'manual'::text, 'recipe'::text])),
    image_url text,
    nutrition_data jsonb,
    consumed_at timestamptz DEFAULT now(),
    created_at timestamptz DEFAULT now(),
    is_hidden boolean DEFAULT false,
    cook_history_id uuid
);

-- 3) Table: recipes
CREATE TABLE IF NOT EXISTS public.recipes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid,
    title text,
    total_cost_rp integer CHECK (total_cost_rp >= 0),
    savings_vs_buying_rp integer DEFAULT 0,
    calories integer DEFAULT 0 CHECK (calories >= 0),
    protein numeric DEFAULT 0 CHECK (protein >= 0::numeric),
    ingredients jsonb,
    steps jsonb,
    is_rice_cooker_only boolean DEFAULT false,
    tools_required text[],
    is_favorite boolean DEFAULT false,
    times_cooked integer DEFAULT 0 CHECK (times_cooked >= 0),
    created_at timestamptz DEFAULT now(),
    last_cooked_at timestamptz
);

-- 4) Table: crowd_contributions
CREATE TABLE IF NOT EXISTS public.crowd_contributions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    contributor_id uuid,
    barcode text,
    product_name text,
    brand text,
    nutrition_data jsonb,
    health_grade text CHECK (health_grade = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text])),
    image_url text,
    upvotes integer DEFAULT 0 CHECK (upvotes >= 0),
    downvotes integer DEFAULT 0 CHECK (downvotes >= 0),
    is_verified boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- 5) Table: accessories
CREATE TABLE IF NOT EXISTS public.accessories (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text,
    description text,
    category text CHECK (category = ANY (ARRAY['hat'::text, 'outfit'::text, 'background'::text, 'pet'::text, 'consumable'::text])),
    price_gold integer CHECK (price_gold >= 0),
    image_url text,
    is_available boolean DEFAULT true,
    required_level integer DEFAULT 1 CHECK (required_level >= 1),
    created_at timestamptz DEFAULT now()
);

-- 6) Table: saved_recipes
CREATE TABLE IF NOT EXISTS public.saved_recipes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid,
    recipe_title text,
    recipe_type text CHECK (recipe_type = ANY (ARRAY['Hemat'::text, 'Balance'::text, 'Premium'::text])),
    description text,
    total_calories integer,
    total_protein integer,
    shopping_cost integer,
    savings_vs_buying integer DEFAULT 0,
    ingredients jsonb DEFAULT '[]'::jsonb,
    cooking_steps jsonb DEFAULT '[]'::jsonb,
    tools_required jsonb DEFAULT '[]'::jsonb,
    is_rice_cooker_only boolean DEFAULT false,
    is_favorite boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    total_carbs numeric DEFAULT 0,
    total_fat numeric DEFAULT 0,
    is_cooked boolean DEFAULT false,
    cooked_at timestamptz,
    gold_earned integer DEFAULT 0,
    xp_earned integer DEFAULT 0,
    first_cooked_at timestamptz,
    last_cooked_at timestamptz,
    times_cooked integer DEFAULT 0
);

-- 7) Table: game_settings
CREATE TABLE IF NOT EXISTS public.game_settings (
    key text PRIMARY KEY,
    value integer,
    description text,
    updated_at timestamptz DEFAULT now()
);

-- 8) Table: recipe_cook_history
CREATE TABLE IF NOT EXISTS public.recipe_cook_history (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    recipe_id uuid,
    user_id uuid,
    cooked_at timestamptz DEFAULT now(),
    gold_earned integer DEFAULT 0,
    xp_earned integer DEFAULT 0,
    hit_daily_limit boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    savings_earned integer DEFAULT 0
);

-- 9) Table: friendships
CREATE TABLE IF NOT EXISTS public.friendships (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_id uuid,
    receiver_id uuid,
    status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Add deleted_at column for soft deletes
ALTER TABLE friendships 
ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;

-- Add index for better query performance
CREATE INDEX idx_friendships_deleted_at ON friendships(deleted_at);

-- Update the view/queries to exclude deleted friendships
-- (This will be handled in application code)


-- ==========================================
-- 2. FOREIGN KEYS
-- ==========================================

-- profiles.id -> auth.users.id
ALTER TABLE IF EXISTS public.profiles 
    ADD CONSTRAINT IF NOT EXISTS profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- friendships.sender_id -> profiles.id
ALTER TABLE IF EXISTS public.friendships 
    ADD CONSTRAINT IF NOT EXISTS friendships_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

-- friendships.receiver_id -> profiles.id
ALTER TABLE IF EXISTS public.friendships 
    ADD CONSTRAINT IF NOT EXISTS friendships_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

-- recipe_cook_history.user_id -> profiles.id
ALTER TABLE IF EXISTS public.recipe_cook_history 
    ADD CONSTRAINT IF NOT EXISTS recipe_cook_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

-- recipe_cook_history.recipe_id -> saved_recipes.id
ALTER TABLE IF EXISTS public.recipe_cook_history 
    ADD CONSTRAINT IF NOT EXISTS recipe_cook_history_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.saved_recipes(id) ON DELETE SET NULL;

-- food_logs.cook_history_id -> recipe_cook_history.id
ALTER TABLE IF EXISTS public.food_logs 
    ADD CONSTRAINT IF NOT EXISTS food_logs_cook_history_id_fkey FOREIGN KEY (cook_history_id) REFERENCES public.recipe_cook_history(id) ON DELETE SET NULL;

-- food_logs.user_id -> profiles.id
ALTER TABLE IF EXISTS public.food_logs 
    ADD CONSTRAINT IF NOT EXISTS food_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

-- recipes.user_id -> profiles.id
ALTER TABLE IF EXISTS public.recipes 
    ADD CONSTRAINT IF NOT EXISTS recipes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

-- saved_recipes.user_id -> auth.users.id
ALTER TABLE IF EXISTS public.saved_recipes 
    ADD CONSTRAINT IF NOT EXISTS saved_recipes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- crowd_contributions.contributor_id -> profiles.id
ALTER TABLE IF EXISTS public.crowd_contributions 
    ADD CONSTRAINT IF NOT EXISTS crowd_contributions_contributor_id_fkey FOREIGN KEY (contributor_id) REFERENCES public.profiles(id) ON DELETE SET NULL;


-- ==========================================
-- 3. ROW LEVEL SECURITY (RLS)
-- ==========================================

ALTER TABLE IF EXISTS public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.food_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.crowd_contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.accessories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.saved_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.game_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.recipe_cook_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.friendships ENABLE ROW LEVEL SECURITY;


-- ==========================================
-- 4. POLICIES
-- ==========================================

-- PROFILES
CREATE POLICY IF NOT EXISTS "Users can view own profile" 
    ON public.profiles FOR SELECT TO authenticated 
    USING ((SELECT auth.uid()) = id);

CREATE POLICY IF NOT EXISTS "Users can insert own profile" 
    ON public.profiles FOR INSERT TO authenticated 
    WITH CHECK ((SELECT auth.uid()) = id);

CREATE POLICY IF NOT EXISTS "Users can update own profile" 
    ON public.profiles FOR UPDATE TO authenticated 
    USING ((SELECT auth.uid()) = id) 
    WITH CHECK ((SELECT auth.uid()) = id);

-- FOOD LOGS
CREATE POLICY IF NOT EXISTS "Users can view own food logs" 
    ON public.food_logs FOR SELECT TO authenticated 
    USING (user_id = (SELECT auth.uid()));

CREATE POLICY IF NOT EXISTS "Users can insert own food logs" 
    ON public.food_logs FOR INSERT TO authenticated 
    WITH CHECK (user_id = (SELECT auth.uid()));

CREATE POLICY IF NOT EXISTS "Users can update own food logs" 
    ON public.food_logs FOR UPDATE TO authenticated 
    USING (user_id = (SELECT auth.uid())) 
    WITH CHECK (user_id = (SELECT auth.uid()));

CREATE POLICY IF NOT EXISTS "Users can delete own food logs" 
    ON public.food_logs FOR DELETE TO authenticated 
    USING (user_id = (SELECT auth.uid()));

-- RECIPES
CREATE POLICY IF NOT EXISTS "Users can view own recipes" 
    ON public.recipes FOR SELECT TO authenticated 
    USING (user_id = (SELECT auth.uid()));

CREATE POLICY IF NOT EXISTS "Users can insert own recipes" 
    ON public.recipes FOR INSERT TO authenticated 
    WITH CHECK (user_id = (SELECT auth.uid()));

CREATE POLICY IF NOT EXISTS "Users can update own recipes" 
    ON public.recipes FOR UPDATE TO authenticated 
    USING (user_id = (SELECT auth.uid())) 
    WITH CHECK (user_id = (SELECT auth.uid()));

-- SAVED RECIPES
CREATE POLICY IF NOT EXISTS "Users can view own saved recipes" 
    ON public.saved_recipes FOR SELECT TO authenticated 
    USING (user_id = (SELECT auth.uid()));

CREATE POLICY IF NOT EXISTS "Users can insert own saved recipes" 
    ON public.saved_recipes FOR INSERT TO authenticated 
    WITH CHECK (user_id = (SELECT auth.uid()));

CREATE POLICY IF NOT EXISTS "Users can update own saved recipes" 
    ON public.saved_recipes FOR UPDATE TO authenticated 
    USING (user_id = (SELECT auth.uid())) 
    WITH CHECK (user_id = (SELECT auth.uid()));

-- RECIPE COOK HISTORY
CREATE POLICY IF NOT EXISTS "Users can view own cook history" 
    ON public.recipe_cook_history FOR SELECT TO authenticated 
    USING (user_id = (SELECT auth.uid()));

CREATE POLICY IF NOT EXISTS "Users can insert own cook history" 
    ON public.recipe_cook_history FOR INSERT TO authenticated 
    WITH CHECK (user_id = (SELECT auth.uid()));

CREATE POLICY IF NOT EXISTS "Users can delete own cook history" 
    ON public.recipe_cook_history FOR DELETE TO authenticated 
    USING (user_id = (SELECT auth.uid()));

-- FRIENDSHIPS
CREATE POLICY IF NOT EXISTS "Users can manage friendships" 
    ON public.friendships FOR ALL TO authenticated 
    USING (sender_id = (SELECT auth.uid()) OR receiver_id = (SELECT auth.uid())) 
    WITH CHECK (sender_id = (SELECT auth.uid()) OR receiver_id = (SELECT auth.uid()));

-- ACCESSORIES & CROWD CONTRIBUTIONS
CREATE POLICY IF NOT EXISTS "Public can read available accessories" 
    ON public.accessories FOR SELECT TO anon 
    USING (is_available = true);

CREATE POLICY IF NOT EXISTS "Authenticated can insert contributions" 
    ON public.crowd_contributions FOR INSERT TO authenticated 
    WITH CHECK (contributor_id = (SELECT auth.uid()));

-- GAME SETTINGS
CREATE POLICY IF NOT EXISTS "Authenticated can read game settings" 
    ON public.game_settings FOR SELECT TO authenticated 
    USING (true);


-- ==========================================
-- 5. INDEXES
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_friendships_sender_id ON public.friendships(sender_id);
CREATE INDEX IF NOT EXISTS idx_friendships_receiver_id ON public.friendships(receiver_id);
CREATE INDEX IF NOT EXISTS idx_food_logs_user_id ON public.food_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_recipe_cook_history_user_id ON public.recipe_cook_history(user_id);
CREATE INDEX IF NOT EXISTS idx_recipes_user_id ON public.recipes(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_recipes_user_id ON public.saved_recipes(user_id);
CREATE INDEX IF NOT EXISTS idx_crowd_contributions_contributor_id ON public.crowd_contributions(contributor_id);
CREATE INDEX IF NOT EXISTS idx_friendships_status ON public.friendships(status);
CREATE INDEX IF NOT EXISTS idx_recipes_created_at ON public.recipes(created_at);


-- ==========================================
-- 6. FUNCTIONS & TRIGGERS (PLACEHOLDERS)
-- ==========================================

-- NOTE: The bodies below are commented out as they were placeholders in the original file.
-- Restore the actual implementation logic inside the BEGIN/END blocks before uncommenting.

/*
CREATE OR REPLACE FUNCTION public.calculate_streak_xp_multiplier()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- original function body omitted; restore actual implementation
    RETURN 1;
END;
$$;
*/

/*
CREATE OR REPLACE FUNCTION public.room_messages_broadcast_trigger()
RETURNS TRIGGER AS $$
BEGIN
    -- PERFORM realtime.broadcast_changes(
    --     'room:' || COALESCE(NEW.room_id, OLD.room_id)::text,
    --     TG_OP,
    --     TG_OP,
    --     TG_TABLE_NAME,
    --     TG_TABLE_SCHEMA,
    --     NEW,
    --     OLD
    -- );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
*/


-- ==========================================
-- 7. GRANTS
-- ==========================================

GRANT USAGE ON SCHEMA public TO authenticated, anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;

-- Ensure future tables inherit grants
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon;

COMMIT;